### ISSUE TITLE
Using flexbox?

### ISSUE THREAD

**Issue by marciobda** [inuitcss/objects.layout#15]
I used inuit in a project almost two years ago and the grid system was great, apart the space issue with inline-block positioning. Using flexbox to build the grid wouldn't solve this?

**Comment by csshugs** [comment]
@marciobda 
Yeah, it would solve this. But if I understand the specification aright, flexbox is not intended to be used for overall page layout, whereas however [CSS Grid Layout](https://medium.com/@patrickbrosset/css-grid-layout-6c9cba6e8a5a) is. 
I admit, [the support is not even close to be production ready](http://caniuse.com/#feat=css-grid), but patience is a virtue ;-)

I was at the same point as you and tinkered around a bit:
http://codepen.io/csshugs/pen/OVovvo
Though, my intention was to be able to produce grid-rows in which the items have the same height in each row, depending on the heighest item in each row (where flexbox is really practical). However it solves your problem and you can omit the HTML-comments as well.

So if you want to use flexbox for the overall page layout (i.e. the grid system), I provided a [inuit-plugin](https://github.com/csshugs/objects.flex-layout).

**Comment by marciobda** [comment]
Thanks for the plugin, @csshugs ! 
That should do the trick.
