### ISSUE TITLE
`o-` prefix 

### ISSUE THREAD

**Issue by fxck** [inuitcss/objects.layout#16]
Wouldn't it make sense to have `o-` as the default prefix? or probably even something like `o-{$inuit-prefix}-layout`

**Comment by fxck** [comment]
Ah, there's already a pull request https://github.com/inuitcss/objects.layout/pull/14/files only with inuit-prefix at the beggining..

**Comment by csshugs** [comment]
@fxck 
There is already [a pull request provided](https://github.com/inuitcss/objects.layout/pull/14). 
Do you mind to close this issue?

**Comment by csshugs** [comment]
Thank you.
