### ISSUE TITLE
Fighting gaps between layout__item

### ISSUE THREAD

**Issue by blai** [inuitcss/objects.layout#7]
So I struggled through the [common problem](http://css-tricks.com/fighting-the-space-between-inline-block-elements/) with doing grid with inline-block (essentially, using `objects.layout` with `trumps.widths`). And I wrap the common solution (using negative margin) in an [inuit module](https://github.com/blai/inuit-layout-zero-gap), and now I can do:

```html
<ul class="layout zero-gap layout-flush">
  <li class="layout__item lap-and-up-1/3">left</li>
  <li class="layout__item lap-and-up-2/3">right</li>
</ul>
```

instead of 

```html
<ul class="layout zero-gap layout-flush">
  <li class="layout__item lap-and-up-1/3">left</li><li class="layout__item lap-and-up-2/3">right</li>
</ul>
```

@csswizardry Is this a valid solution from your perspective. Do you want to adopt the module (I will transfer repository ownership to you)

**Comment by florianbouvot** [comment]
I don't think that @csswizardry will add any solution like this to is framework.

You can add negative margin solution in your own code or use this unofficial solution based on font-size zero method : https://github.com/tweeb/objects.layout-whitespace-fix

**Comment by csswizardry** [comment]
Yeah, I’m afraid that nothing like this will make its way into the framework. The only failsafe, zero-side-effects way to remove the whitespace is to actually remove the whitespace. Everything else is either not guaranteeable, or can have weird side effects and outcomes.
